### ISSUE TITLE
FosUserbundle and Api authenticate

### ISSUE THREAD

**Issue by meron1122** [uecode/api-key-bundle#19]
My config:
![bez tytulu](https://cloud.githubusercontent.com/assets/2895090/7641688/9ff119de-fa8b-11e4-8da5-14896b7dda0f.png)
When i execute:
`http://warehouse.dev/app_dev.php/api/hello?api_key=MmJmY2YzMGQzMzQ2ZDRmOWM1NmY3NDRiMmY2YzFkOWM0Y2YzMW`

Symfony redirect me to FosUserBundle login page.
What I'm doing wrong with my configuration?

**Comment by aequasi** [comment]
Not sure.... Maybe put the api firewall before the main firewall?

**Comment by meron1122** [comment]
When i move this, i can anonymously access to /api/*.
Maybe i had a bad providers config?

**Comment by aequasi** [comment]
Check the last line in your `access_control`

**Comment by meron1122** [comment]
If i change to ``ROLE_USER`` then  FosUserBundle handle login, i don't have idea how config to authenticate  ``/`` via FosUserBundle and ``/api/*`` via Your bundle.

**Comment by aequasi** [comment]
If you put the api firewall on top, and remove the last access_control line you have regarding the api, it should work.

**Comment by meron1122** [comment]
Thanks for reply again, little progress:
``No Authentication Provider found for token of class "Uecode\Bundle\ApiKeyBundle\Security\Authentication\Token\ApiKeyUserToken".``

**Comment by aequasi** [comment]
I'm not really sure from there. Try setting up the chain provider, like in the README.md

**Comment by aequasi** [comment]
I'm unfortunately not that great with the security stuff

**Comment by meron1122** [comment]
```
    providers:
        db:
            id: uecode.api_key.provider.user_provider

    firewalls:
        api:
            pattern: ^/api/
            api_key: true
            stateless: true
            provider: db  #here
```
This solved issue, thanks.
Maybe add this piece of code to readme?
