### ISSUE TITLE
No Authentication Provider found for token of class "ApiKeyUserToken".

### ISSUE THREAD

**Issue by L0rD59** [uecode/api-key-bundle#3]
Hi,

I've some trouble with your bundle.

I've got this error : `No Authentication Provider found for token of class "Uecode\Bundle\ApiKeyBundle\Security\Authentication\Token\ApiKeyUserToken".`

My `config.yml` : 

```
#FOS User Configuration
fos_user:
   db_driver: orm
   firewall_name: auth
   user_class: LIG\Bundle\UserBundle\Entity\UserApi
```

My `security.yml` : 

```
security:
    providers:
        db:
            id: uecode.api_key.provider.user_provider
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/api/.*
            api_key: true
            stateless: true
```

Can you tell me what's wrong ?

Thx a lot for your time.

Best regards
